name: Deploy to ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ecs-task:
    uses: aba-enterprise/enterprise-ci-templates/.github/workflows/ecr-task-template.yml@main
    with:
      cluster-name: "test-ecs-cluster"
      task-family: "ecs-test-task"
      container-name: "ecs-test-container"
      ecr-repo: "nonprodimagerepository"
      aws-accountid: "707733857215"

  ecs-service:
    needs: ecs-task
    uses: aba-enterprise/enterprise-ci-templates/.github/workflows/ecs-service-template.yml@main
    with:
      cluster-name: "test-ecs-cluster"
      service-name: "WeatherForecast_api"
      task-family: "ecs-test-task"
      subnets: "subnet-05741c5e17cae42e3,subnet-08a31fa8b5dec1cfa"
      security-groups: "sg-063ac0f34f2c86baa"
      desired-count: "1"
      aws-accountid: "707733857215"
