
name: CI/CD .Net core App

on:
  push:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write
  id-token: write       # ✅ Needed for OIDC with AWS

jobs:
  dotnet-ci:
    name: .NET Build and Containerization
    uses: aba-enterprise/enterprise-ci-templates/.github/workflows/ecr-template.yml@main
    with:
      project-path: './dotnet-ecs-sample/dotnet-ecs-sample.csproj'
      dockerfile-path: './dotnet-ecs-sample/Dockerfile'
      image-name: 'dotnet-ecs-sample'
      # ecr-repo: nonprodimagerepository   # ✅ AWS ECR repo